Update codeql-analysis.yml

diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -28,9 +28,14 @@ jobs:
       with:
         files: |
           .github
+          
+    - name: Verify changed files
+      if: steps.changed_files.outputs.any_changed == 'false'
+      run: |
+        echo "::error::Changed files detected in .github directory: ${{ steps.changed_files.outputs.all_changed_files }}"
+        exit 1
 
     - name: Initialize CodeQL
-      if: steps.changed_files.outputs.any_changed == 'false'
       uses: github/codeql-action/init@v1
       with:
         languages: ${{ matrix.language }}
